on script load:
    set {-sql} to the database "mysql://192.168.50.220:3306/user_data?user=root&password=mc_159159159&useSSL=false"
    send "Loaded Database" to console

command /database:
    trigger:
        set {_test} to "command time"
        execute "INSERT INTO `user_data` (`uuid`,`username`,`lastjoin`) VALUES (%uuid of player%,%name of player%,%rounded unix timestamp of now%) ON DUPLICATE KEY UPDATE `username`=VALUES(`username`),`lastjoin`=VALUES(`lastjoin`)" in {-sql}
        execute "select * from user_data WHERE uuid = %player's uuid% LIMIT 1" in {-sql} and store the result in {_output::*}
        send "%{_test}% | %{_output::username::*}%" to player